name: Build and Deploy to GKE

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ develop ]

jobs:
  setup-build-publish-deploy:
    name: Build and Push Docker
    runs-on: ubuntu-latest
    environment: test

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Configure Docker login
    - run: |-
        docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  

    # Build the Docker image
    - name: Build
      run: |-
        docker build -t "asingh01/test-images:webserver" .

    # Push the Docker image to Google Container Registry
    - name: Publish
      run: |-
        docker push "asingh01/test-images:webserver"
    
    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        service_account_key: ${{ secrets.SERVICE_ACCOUNT }}
        project_id: ${{ secrets.PROJECT_ID }}

    # Setup Terraform
    - uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.13.5

